// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efeawcywdijesciyztbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmZWF3Y3l3ZGlqZXNjaXl6dGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjY5MDQsImV4cCI6MjA2NzY0MjkwNH0.10ANrnn1xsjGbTs_G7w2GXoGWqGmrw-KaG4aStoZ8NY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});